version: 2
updates:
  # Main package.json for npm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    versioning-strategy: increase
    groups:
      minor-and-patch-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: "deps"
      include: "scope"
    ignore:
      # Ignore major version updates to React which would need more careful testing
      - dependency-name: "react*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@types/react*"
        update-types: ["version-update:semver-major"]

  # API directory package.json for npm dependencies
  - package-ecosystem: "npm"
    directory: "/api"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    versioning-strategy: increase
    groups:
      api-dependencies:
        patterns:
          - "*"
    commit-message:
      prefix: "deps(api)"
      include: "scope"

  # GitHub Actions workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    commit-message:
      prefix: "ci"
      include: "scope"