packages:
  - packages/*

catalog:
  '@biomejs/biome': ^2.0.2
  react: ^19.0.0
  react-dom: ^19.0.0
  zod: ^3.25.58
  tsx: ^4.20.3
  typescript: ^5.8.3
  wrangler: ^4.20.5
  '@cloudflare/workers-types': ^4.20250620.0
  '@types/node': ^22.15.32
  '@types/react': ^19.1.7
  '@types/react-dom': ^19.1.6
  drizzle-kit: ^0.31.1
  alchemy: ^0.37.1
  http-status-codes: ^2.3.0
  dotenv: 16.5.0
  drizzle-orm: ^0.44.2
  drizzle-seed: ^0.3.1
  drizzle-zod: 0.7.1
  concurrently: ^9.1.2
  wait-on: ^8.0.3
