name: Validate

on:
  pull_request:
    branches:
      - master

jobs:
  typecheck:
    runs-on: ubuntu-latest
    name: Check TypeScript Types
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: true

      - name: Check types
        run: pnpm types

  lint-and-format:
    runs-on: ubuntu-latest
    name: Run Biome Linter and Formatter
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: true

      - name: Setup Biome CLI
        uses: biomejs/setup-biome@v2
        
      - name: Run Biome
        run: biome ci
